In [ ]:
import numpy as np
arr=np.arange ( 5 , 51 , 5 )
for index , val in enumerate ( arr ) :
    print(f'5 x { index +1} = {val} ' )

5 x 1 = 5 
5 x 2 = 10 
5 x 3 = 15 
5 x 4 = 20 
5 x 5 = 25 
5 x 6 = 30 
5 x 7 = 35 
5 x 8 = 40 
5 x 9 = 45 
5 x 10 = 50 


In [ ]:
print(list(arr))

[np.int64(5), np.int64(10), np.int64(15), np.int64(20), np.int64(25), np.int64(30), np.int64(35), np.int64(40), np.int64(45), np.int64(50)]


In [ ]:
arr_2 = np.array ( ( [1 , 2 ,3 ] , [3 , 4 ,5 ] ) ,dtype = float )
print(type(arr_2))
arr_2    #A two dimensional array


<class 'numpy.ndarray'>


array([[1., 2., 3.],
       [3., 4., 5.]])

In [ ]:
arr_2 //= 0.5
#Will use '//' because array is float type
print(arr_2)


[[ 4.  8. 12.]
 [12. 16. 20.]]


In [ ]:
arr_2 + arr_2

array([[ 8., 16., 24.],
       [24., 32., 40.]])

In [ ]:
print(arr_2.shape)
#(2,3) means 2 row and 3 column
print(arr_2.dtype )

(2, 3)
float64


In [ ]:
data  =  [ [ 1 ,  2 , 3 ] , [ 2, 3 ,4 ] ]
print(np.array(data).ndim)
#A two dimensional array

2


In [ ]:
arr = np.zeros( ( 3,4) , dtype= int)
print(arr.ndim)
print(arr, arr.shape )
print(type( arr.shape))

2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
<class 'tuple'>


In [ ]:
np.empty?




Docstring:
empty(shape, dtype=float, order='C', *, device=None, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: ``None``.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it

In [ ]:
b = np.empty( (2,3 ) ,  dtype = int )
print(b) #Garbage values

[[4620693217682128896 4625196817309499392 4627448617123184640]
 [4627448617123184640 4629700416936869888 4630826316843712512]]


In [ ]:
arr = np.ones ( ( 4,3  ,4
                ))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.asarray( [ (1,2,3) ,
              (4 , 2 ,6 ) ]
          )

array([[1, 2, 3],
       [4, 2, 6]])

In [ ]:
np.asarray(arr )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
int_arr = np.array( list(range(0,11)) )
print(int_arr.dtype)

int64


In [ ]:
float_arr = int_arr.astype ( np.float64 )
print(float_arr.dtype )
#Converted the data type, the array object has the method of astype , and the argument

float64


In [ ]:
class Dog () :
    def __init__ ( self , name ) :
        self.name = name

    def speak ( self ) :
        print(f'{self.name} is speaking' )

def my_fn ( obj , method ) :
    method(obj)

dog  = Dog('harry')
my_fn( dog , Dog.speak)

def create_and_speak ( cls , name ) :
    ins = cls(name)
    ins.speak()
create_and_speak ( Dog , 'rex' )

#Passing instance or method as refernce in arguments causes us to decide what to do with it later

harry is speaking
rex is speaking


In [ ]:
arr = np.arange ( 1 , 21 , 0.8931 )
print(arr.dtype)
print(arr)
#By converting to integer decimal points will be ignored
arr = arr.astype ( np.int64)
print(arr , arr.dtype)

float64
[ 1.      1.8931  2.7862  3.6793  4.5724  5.4655  6.3586  7.2517  8.1448
  9.0379  9.931  10.8241 11.7172 12.6103 13.5034 14.3965 15.2896 16.1827
 17.0758 17.9689 18.862  19.7551 20.6482]
[ 1  1  2  3  4  5  6  7  8  9  9 10 11 12 13 14 15 16 17 17 18 19 20] int64


In [ ]:
arr = np.array ( [ '1' , '2' , '4' ] , dtype = np.str_)
#I can set dtype = str , dtype = np.str_ in both ways
#Also when doing conversion , .astype ( float ) or  .astype( np.float64) in both ways
print(arr.dtype)
print(arr )


<U1
['1' '2' '4']


In [ ]:
arr_1 = np.arange ( 1, 19 ,2)
#So arange method only generates 1d array
print(arr_1 , arr_1.ndim )
#the arr_1 is the instance when printing we get the value because inside its class it has __str__ method()
#which does this , otherwise an object address is usually shown in the terminal

[ 1  3  5  7  9 11 13 15 17] 1


In [ ]:
arr_1.reshape ( 3,3
              )

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
arr_1 = np.array ( [
    [ 1 , 2 , 3 ] ,
    [ 9, 12, 51 ] ,
    [ 90, 53, 131 ]
] )
print(arr_1.shape)
print(arr_1)
# print(arr_1.reshape( 3,3, 1))
#Shape ( layers, rows, columns )

(3, 3)
[[  1   2   3]
 [  9  12  51]
 [ 90  53 131]]


In [ ]:
arr_2 = np.array ( [
    [ x**1.4 for x in range (1,4) ] ,
    [ x**1.2 for x in range (1,4) ] ,
    [ x**1.5 for x in range (1,4) ] ]
                 )
print(arr_2,arr_2.dtype)


[[1.         2.63901582 4.65553672]
 [1.         2.29739671 3.73719282]
 [1.         2.82842712 5.19615242]] float64


In [ ]:
arr_1 + arr_2

array([[  2.        ,   4.63901582,   7.65553672],
       [ 10.        ,  14.29739671,  54.73719282],
       [ 91.        ,  55.82842712, 136.19615242]])

In [ ]:
val = arr_1>arr_2
print(val)
print(type(val) , val.dtype)
#So comparison changes the dtype to be boolean data type

[[False False False]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'> bool


In [ ]:
arr_1 == arr_2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])