In [27]:
lst =  list ( range ( 1 , 21 )) 
for i , n in enumerate (lst) :
    if n % 3 == 0 :
        lst[i] = 'three(x)'
    elif n % 2 == 0 :
        lst[i] = 'two(x)'
    else :
        pass
lst



[1,
 'two(x)',
 'three(x)',
 'two(x)',
 5,
 'three(x)',
 7,
 'two(x)',
 'three(x)',
 'two(x)',
 11,
 'three(x)',
 13,
 'two(x)',
 'three(x)',
 'two(x)',
 17,
 'three(x)',
 19,
 'two(x)']

In [29]:
matrix = [ [1 , 2 ,3 ] ,
           [4 , 5 , 6 ],
           [7 , 8 , 9 ] ]
sum_of =  [] 
for index , val in enumerate (matrix) :
    s =  sum(matrix[index] )
    sum_of.append( s )
sum_of

    
    

[6, 15, 24]

In [16]:
str.replace?

Signature: str.replace(self, old, new, count=-1, /)
Docstring:
Return a copy with all occurrences of substring old replaced by new.

  count
    Maximum number of occurrences to replace.
    -1 (the default value) means replace all occurrences.

If the optional argument count is given, only the first count occurrences are
replaced.
Type:      method_descriptor

In [43]:
import numpy as np 
my_arr = np.arange ( 10 )
print ( my_arr )
print(type( my_arr ))
#so np.arange ( ) creates an array ,
#And numpy arrays are much faster than python lists

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [44]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [50]:
a = np.array ( range(1,100) )
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
<class 'numpy.ndarray'>


In [54]:
#So np.ndarray is a class not the function 
#this is because this lib was created before CamelCase was adopted
#so 'a' is the instance created  from the np.ndarray class
class Person:
    def __init__(self, name):
        self.name = name

p = Person("Alex")  # function call creates object
print(type(p) )             # <class '__main__.Person'>

#See 'p' is not the class but the object of person



<class '__main__.Person'>


In [65]:
import numpy as np
array = np.array ( [x for x in range(1,11) ] )
print(array)

#The array() method takes an object and coverts into an array

arr_2 =  np.array ( tuple(x**2 for x in range ( 1 ,11 )) )
print(arr_2)

#The arange method() takes start stop , step argumetns too
arr_3 = np.arange ( 2 , 21 , 2 )
print(arr_3)


#Perfoming vectorized operation
arr_3*= 10
print(arr_3)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]
[ 2  4  6  8 10 12 14 16 18 20]
[ 20  40  60  80 100 120 140 160 180 200]
